version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: user
    ports:
      - "5001:5432"  # Port to expose Postgres (not 5001)
    networks:
      - app_network

  fastapi:
    build: .
    container_name: fastapi
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://user:1234@database:5432/user
    ports:
      - "8001:8001"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
